#!/usr/bin/env python3
''' CLI DNSBL checker

MIT License — this software is open source.

Copyright © 2021, Yarema <yds@Necessitu.de>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'''
import sys
import yaml
import socket
import argparse
from dns.resolver import *
resolver = Resolver()
resolver.search = False

__version__ = '0.1.0'
encoding = 'utf-8'
check = ('https://MultiRBL.Valli.org/lookup/{}.html',
         'https://HetrixTools.com/blacklist-check/{}')
conf = '/etc/dnsbl.yml'
LRED = '\033[1;31m'
LGRN = '\033[1;32m'
NRML = '\033[m'

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
def resolve(qname, rdtype='A'):
    '''resolve hostname'''
    try:
        return resolver.resolve(qname, rdtype)
    except (NoAnswer, NXDOMAIN) as e:
        msg = str(e).split(':')[0]
    except NoNameservers as e:
        msg = ' '.join(str(e).split(' IN A: ')[0].split()[:-1])
    except Timeout as e:
        msg = str(e)
    if args.v:
        print(f'{LRED}{msg}{LGRN}: {rdtype}{NRML} {qname}', file=sys.stderr)
    return None

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
def query(addr):
    '''query if given IP address is blacklisted'''
    zones = yaml.load(open(conf), Loader=yaml.CSafeLoader)
    addr = socket.gethostbyname(addr)
    reverse = '.'.join(reversed(addr.split('.')))
    results = []
    for zone in sorted(zones.keys(), key=lambda k: tuple(reversed(k.split('.')))):
        dnsbl = f'{reverse}.{zone}.'
        result = resolve(dnsbl)
        if result:
            txt = resolve(dnsbl, 'TXT')
            dnsbl = [dnsbl]
            if zones[zone]:
                dnsbl += reversed(zones[zone].format(addr).split('\t'))
            if txt:
                dnsbl += [str(s).strip('"') for s in txt.rrset]
            results.append((dnsbl, result))
    if results:
        print(f'\n\t{addr} is BLACKLISTED:\n')
        for txt in check: print(txt.format(addr))
        for dnsbl, result in results:
            print()
            if len(dnsbl) > 1:
                for txt in dnsbl[1:]:
                    print(txt)
            for txt in result:
                print(f'[{txt}]\t{dnsbl[0]}')
        return tuple(results)
    return None

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
def multirbl(zones={}, verbose=False):
    '''dump sorted YAML of "alive" DNSBL zones from MultiRBL.Valli.org'''
    from urllib.request import urlopen
    from html.parser import unescape
    with urlopen('https://MultiRBL.Valli.org/list/') as multirbl:
        start = '<h2>dead' if zones else '<h2>alive'
        parse = False
        table = False
        for zone in multirbl:
            zone = unescape(zone.decode(encoding).strip()).split('</td><td>')
            if zone[0].startswith(start):
                parse = True
            elif zone[0] == '</table>':
                parse = False
                table = False
            elif table:
                if start == '<h2>alive' and zone[3] == 'ipv4' and zone[6] == 'b' and '.' in zone[2]:
                    zone[1] = zone[1].split('"')
                    zone[1][2] = zone[1][2][1:].split('<')[0].strip()
                    zones[zone[2]] = f'{zone[1][1]}\t{zone[1][2]}'
                elif start == '<h2>dead' and zone[2] in zones:
                    del zones[zone[2]]
            elif parse and zone[0] == '<table>':
                table = True
    if verbose:
        for zone in sorted(zones.keys(), key=lambda k: tuple(reversed(k.split('.')))):
            print(f'{zone}: {zones[zone]}')
    return zones

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
def zones():
    '''dump sorted YAML of local DNSBL zones merged with current MultiRBL zones'''
    multi = multirbl()              # load all "alive" MultiRBL zones
    zones = {**multi, **yaml.load(open(conf), Loader=yaml.CSafeLoader)} # merge local zones
    zones = multirbl(zones=zones)   # prune "dead" zones
    for zone in sorted(zones.keys(), key=lambda k: tuple(reversed(k.split('.')))):
        if zones[zone]:
            zones[zone] = f' {zones[zone]}'
        elif zone in multi:
            zones[zone] = f' {multi[zone]}'
        else:
            zones[zone] = ''
        print(f'{zone}:{zones[zone]}')
    return zones

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
if __name__ == '__main__':
    args = argparse.ArgumentParser(
        description='dnsbl checks if an IP address is blacklisted by any of '
                    'the DNSBL sevices commonly subscribed by SPAM filters.')
    args.add_argument('-l', action='store_true', help='List merged MultiRBL zones')
    args.add_argument('-m', action='store_true', help='List only MultiRBL zones')
    args.add_argument('-v', action='store_true', help='Print verbose results')
    args.add_argument('host', type=str, nargs='?', help='FQDN or IP address to check')
    args = args.parse_args()
    if args.host: query(args.host)
    elif  args.l: zones()
    elif  args.m: multirbl(verbose=True)
    else: sys.exit(f'{LRED}Please specify a FQDN or IP address as a parameter.{NRML}')

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
# EOF
